export interface VPSPlan {
  id: string;
  name: string;
  category: 'budget' | 'standard' | 'performance' | 'power';
  monthlyPriceINR: number;
  monthlyPriceUSD: number;
  vcpu: number;
  ramGB: number;
  storageNVMeGB: number;
  bandwidth: string;
  ipv4: string;
  virtualization: string;
  ddosProtection: string;
  snapshots: string;
  popular?: boolean;
  badge?: string;
  highlight?: string;
  cpuArchitecture: string;
  ramType: string;
  description: string;
}

export interface GamePlan {
  id: string;
  gameId: string;
  gameName: string;
  ramGB: number;
  vcpu: number;
  storageNVMeGB: number;
  monthlyPriceINR: number;
  monthlyPriceUSD: number;
  playerSlots: string;
  location: string;
  isAvailable: boolean;
}

export interface DatacenterLocation {
  id: string;
  country: string;
  flag: string;
  city: string;
  facility: string;
  status: string;
  statusColor: string;
  description: string;
  isConfirmed: boolean;
  latency: string;
  testIP: string;
}

export interface SystemStatusItem {
  id: string;
  name: string;
  status: 'Operational' | 'Degraded' | 'Maintenance';
  state: 'green' | 'yellow' | 'red';
  detail: string;
}

export const KRYONHOST_CONFIG = {
  brand: {
    name: 'KryonHost',
    domain: 'kryonhost.com',
    tagline: 'Powerful Infrastructure. Built for What\'s Next.',
    subtext: 'High-performance VPS and game hosting without the enterprise price tag.',
    status: 'Infrastructure Online',
  },

  contact: {
    email: 'support@kryonhost.com',
    phone: '+91 8750287172',
    hours: '9:00 AM – 5:00 PM IST (Mon – Sat)',
    discordUrl: 'https://discord.gg/kryonhost',
    twitterUrl: 'https://x.com/kryonhost',
    githubUrl: 'https://github.com/kryonhost',
  },

  // Trust Strip Items
  trustStrip: [
    { label: 'KVM Virtualization', detail: 'Hardware-Isolated VMs' },
    { label: 'NVMe Storage', detail: 'Gen4/Gen5 PCIe Speeds' },
    { label: 'DDoS Protection', detail: 'Always-On Filtering' },
    { label: 'Instant Provisioning', detail: 'Automated Deployment' },
    { label: '1 Gbps Network', detail: 'High IOPS & Connectivity' },
    { label: '24/7 Infrastructure Monitoring', detail: 'Real-Time Telemetry' },
  ],

  // Datacenter Locations
  locations: [
    {
      id: 'in-mumbai',
      country: 'India',
      flag: '🇮🇳',
      city: 'Mumbai',
      facility: 'Tier IV Datacenter',
      status: 'Operational',
      statusColor: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30',
      description: 'Primary Tier IV facility located in Navi Mumbai with direct NIXI and ExtremeIX peering.',
      isConfirmed: true,
      latency: '< 5ms',
      testIP: '103.186.20.1',
    },
  ] as DatacenterLocation[],

  // VPS Centralized Data Structure
  vpsCategories: [
    {
      id: 'budget',
      name: 'BUDGET VPS',
      tagline: 'Intel Xeon V3/V4 • KVM • NVMe • Unlimited Bandwidth',
      description: 'Cost-effective KVM compute for development, light web servers, bots, and personal projects.',
      cpuSpec: 'Intel Xeon V3 / V4 Processor',
      ramType: 'DDR4 RAM',
      network: 'Unlimited Bandwidth',
    },
    {
      id: 'standard',
      name: 'STANDARD VPS',
      tagline: 'AMD EPYC 7002/7003 • DDR4 ECC • KVM • 1 Gbps',
      description: 'Balanced enterprise multi-core performance for business applications, databases, and microservices.',
      cpuSpec: 'AMD EPYC 7302 / 7402 / 7542',
      ramType: 'DDR4 ECC RAM',
      network: '1 Gbps Shared Network',
    },
    {
      id: 'performance',
      name: 'PERFORMANCE VPS',
      tagline: 'Intel 12th/13th Gen • High Single-Core • Game-Server Ready',
      description: 'Ultra-high clock speed compute engineered for game servers, high-concurrency APIs, and heavy workloads.',
      cpuSpec: 'Intel 12th / 13th Gen (i5-12600K / i7-13700K)',
      ramType: 'DDR4 High-Speed RAM',
      network: '1 Gbps Shared Network',
      highlightBadge: 'HIGH SINGLE-CORE PERFORMANCE',
    },
    {
      id: 'power',
      name: 'POWER VPS',
      tagline: 'AMD Ryzen 7000 Series (X/X3D) • DDR5 Memory • Max Performance',
      description: 'Top-tier compute featuring AMD Ryzen 7000 X3D processors and next-gen DDR5 memory.',
      cpuSpec: 'AMD Ryzen 5 / 7 / 9 7000 Series (X / X3D)',
      ramType: 'DDR5 ECC RAM',
      network: '1 Gbps Shared Network',
      highlightBadge: 'MAXIMUM PERFORMANCE & DDR5',
    },
  ],

  // All Customer-Facing VPS Plans
  vpsPlans: [
    // --- BUDGET VPS ---
    {
      id: 'budget-4gb',
      name: '4 GB VPS',
      category: 'budget',
      monthlyPriceINR: 379,
      monthlyPriceUSD: 4.75,
      vcpu: 2,
      ramGB: 4,
      storageNVMeGB: 10,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: 'Starter budget instance for lightweight workloads and scripts.',
    },
    {
      id: 'budget-8gb',
      name: '8 GB VPS',
      category: 'budget',
      monthlyPriceINR: 459,
      monthlyPriceUSD: 5.75,
      vcpu: 4,
      ramGB: 8,
      storageNVMeGB: 50,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      popular: true,
      badge: 'MOST POPULAR BUDGET',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: 'Popular budget configuration for Discord bots, VPNs, and web servers.',
    },
    {
      id: 'budget-16gb',
      name: '16 GB VPS',
      category: 'budget',
      monthlyPriceINR: 749,
      monthlyPriceUSD: 9.35,
      vcpu: 6,
      ramGB: 16,
      storageNVMeGB: 60,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: 'Ample memory for multi-container Docker applications.',
    },
    {
      id: 'budget-24gb',
      name: '24 GB VPS',
      category: 'budget',
      monthlyPriceINR: 1149,
      monthlyPriceUSD: 14.35,
      vcpu: 8,
      ramGB: 24,
      storageNVMeGB: 80,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: 'High memory instance for database and staging servers.',
    },
    {
      id: 'budget-32gb',
      name: '32 GB VPS',
      category: 'budget',
      monthlyPriceINR: 1549,
      monthlyPriceUSD: 19.35,
      vcpu: 10,
      ramGB: 32,
      storageNVMeGB: 100,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: '32 GB RAM budget node for memory-heavy applications.',
    },
    {
      id: 'budget-48gb',
      name: '48 GB VPS',
      category: 'budget',
      monthlyPriceINR: 2249,
      monthlyPriceUSD: 28.10,
      vcpu: 12,
      ramGB: 48,
      storageNVMeGB: 150,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: '48 GB RAM instance for high-throughput background processing.',
    },
    {
      id: 'budget-64gb',
      name: '64 GB VPS',
      category: 'budget',
      monthlyPriceINR: 2949,
      monthlyPriceUSD: 36.85,
      vcpu: 14,
      ramGB: 64,
      storageNVMeGB: 250,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: 'Heavy compute node with 64 GB memory and 250 GB NVMe.',
    },
    {
      id: 'budget-96gb',
      name: '96 GB VPS',
      category: 'budget',
      monthlyPriceINR: 4649,
      monthlyPriceUSD: 58.10,
      vcpu: 16,
      ramGB: 96,
      storageNVMeGB: 300,
      bandwidth: 'Unlimited Bandwidth',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'Intel Xeon V3 / V4',
      ramType: 'DDR4 RAM',
      description: 'Maximum budget tier with 96 GB RAM and 16 vCPU cores.',
    },

    // --- STANDARD VPS ---
    {
      id: 'standard-4gb',
      name: '4 GB VPS',
      category: 'standard',
      monthlyPriceINR: 616,
      monthlyPriceUSD: 7.70,
      vcpu: 2,
      ramGB: 4,
      storageNVMeGB: 30,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'AMD EPYC 7302 / 7402',
      ramType: 'DDR4 ECC RAM',
      description: 'Enterprise EPYC core compute for production microservices.',
    },
    {
      id: 'standard-8gb',
      name: '8 GB VPS',
      category: 'standard',
      monthlyPriceINR: 871,
      monthlyPriceUSD: 10.88,
      vcpu: 4,
      ramGB: 8,
      storageNVMeGB: 60,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      popular: true,
      badge: 'POPULAR STANDARD',
      cpuArchitecture: 'AMD EPYC 7302 / 7402',
      ramType: 'DDR4 ECC RAM',
      description: 'Balanced EPYC server for web applications and API gateways.',
    },
    {
      id: 'standard-16gb',
      name: '16 GB VPS',
      category: 'standard',
      monthlyPriceINR: 1424,
      monthlyPriceUSD: 17.80,
      vcpu: 6,
      ramGB: 16,
      storageNVMeGB: 100,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'AMD EPYC 7302 / 7402',
      ramType: 'DDR4 ECC RAM',
      description: 'Solid 6-core EPYC performance for production databases.',
    },
    {
      id: 'standard-24gb',
      name: '24 GB VPS',
      category: 'standard',
      monthlyPriceINR: 2019,
      monthlyPriceUSD: 25.23,
      vcpu: 8,
      ramGB: 24,
      storageNVMeGB: 120,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'AMD EPYC 7302 / 7402',
      ramType: 'DDR4 ECC RAM',
      description: '8 vCPU AMD EPYC server with 24 GB ECC memory.',
    },
    {
      id: 'standard-32gb',
      name: '32 GB VPS',
      category: 'standard',
      monthlyPriceINR: 2699,
      monthlyPriceUSD: 33.73,
      vcpu: 10,
      ramGB: 32,
      storageNVMeGB: 160,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'AMD EPYC 7302 / 7402',
      ramType: 'DDR4 ECC RAM',
      description: 'High-density EPYC node for complex cloud workloads.',
    },
    {
      id: 'standard-64gb',
      name: '64 GB VPS',
      category: 'standard',
      monthlyPriceINR: 4824,
      monthlyPriceUSD: 60.30,
      vcpu: 12,
      ramGB: 64,
      storageNVMeGB: 300,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      cpuArchitecture: 'AMD EPYC 7302 / 7402',
      ramType: 'DDR4 ECC RAM',
      description: '12 vCPU 64 GB RAM EPYC instance for enterprise operations.',
    },

    // --- PERFORMANCE VPS ---
    {
      id: 'performance-4gb',
      name: '4 GB VPS',
      category: 'performance',
      monthlyPriceINR: 829,
      monthlyPriceUSD: 10.36,
      vcpu: 2,
      ramGB: 4,
      storageNVMeGB: 30,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'High Single-Core Speed',
      cpuArchitecture: 'Intel 12th/13th Gen i5-12600K',
      ramType: 'DDR4 High-Speed RAM',
      description: 'Fast single-core performance for active backend services.',
    },
    {
      id: 'performance-8gb',
      name: '8 GB VPS',
      category: 'performance',
      monthlyPriceINR: 1254,
      monthlyPriceUSD: 15.67,
      vcpu: 4,
      ramGB: 8,
      storageNVMeGB: 60,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'Game-Server Ready',
      cpuArchitecture: 'Intel 12th/13th Gen i5-13600K',
      ramType: 'DDR4 High-Speed RAM',
      description: 'Great choice for high-tickrate game servers and fast APIs.',
    },
    {
      id: 'performance-16gb',
      name: '16 GB VPS',
      category: 'performance',
      monthlyPriceINR: 2019,
      monthlyPriceUSD: 25.23,
      vcpu: 6,
      ramGB: 16,
      storageNVMeGB: 100,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      popular: true,
      badge: 'POPULAR PERFORMANCE',
      highlight: 'Game-Server Ready',
      cpuArchitecture: 'Intel 12th/13th Gen i7-13700K',
      ramType: 'DDR4 High-Speed RAM',
      description: 'Optimal setup for heavily modded Minecraft, Rust, and Node servers.',
    },
    {
      id: 'performance-24gb',
      name: '24 GB VPS',
      category: 'performance',
      monthlyPriceINR: 2869,
      monthlyPriceUSD: 35.86,
      vcpu: 8,
      ramGB: 24,
      storageNVMeGB: 120,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'High Single-Core Speed',
      cpuArchitecture: 'Intel 12th/13th Gen i7-13700K',
      ramType: 'DDR4 High-Speed RAM',
      description: '8-core Intel high-clock instance with 24 GB RAM.',
    },
    {
      id: 'performance-32gb',
      name: '32 GB VPS',
      category: 'performance',
      monthlyPriceINR: 3804,
      monthlyPriceUSD: 47.55,
      vcpu: 10,
      ramGB: 32,
      storageNVMeGB: 160,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'Game-Server Ready',
      cpuArchitecture: 'Intel 12th/13th Gen i7-13700K',
      ramType: 'DDR4 High-Speed RAM',
      description: '32 GB RAM high single-core compute node.',
    },
    {
      id: 'performance-64gb',
      name: '64 GB VPS',
      category: 'performance',
      monthlyPriceINR: 6949,
      monthlyPriceUSD: 86.86,
      vcpu: 12,
      ramGB: 64,
      storageNVMeGB: 300,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'High Single-Core Speed',
      cpuArchitecture: 'Intel 12th/13th Gen i7-13700K',
      ramType: 'DDR4 High-Speed RAM',
      description: '12 vCPU Intel high-clock performance node with 64 GB RAM.',
    },

    // --- POWER VPS ---
    {
      id: 'power-4gb',
      name: '4 GB VPS',
      category: 'power',
      monthlyPriceINR: 829,
      monthlyPriceUSD: 10.36,
      vcpu: 2,
      ramGB: 4,
      storageNVMeGB: 30,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'Ryzen 7000 Series • DDR5',
      cpuArchitecture: 'AMD Ryzen 5 7600X / 7700X',
      ramType: 'DDR5 ECC RAM',
      description: 'Next-gen Ryzen 7000 series compute with DDR5 memory speeds.',
    },
    {
      id: 'power-8gb',
      name: '8 GB VPS',
      category: 'power',
      monthlyPriceINR: 1254,
      monthlyPriceUSD: 15.67,
      vcpu: 4,
      ramGB: 8,
      storageNVMeGB: 60,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'Maximum Single-Core Performance',
      cpuArchitecture: 'AMD Ryzen 7 7700X / 7800X3D',
      ramType: 'DDR5 ECC RAM',
      description: 'Blazing fast Ryzen performance with DDR5 RAM.',
    },
    {
      id: 'power-16gb',
      name: '16 GB VPS',
      category: 'power',
      monthlyPriceINR: 2019,
      monthlyPriceUSD: 25.23,
      vcpu: 6,
      ramGB: 16,
      storageNVMeGB: 100,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      popular: true,
      badge: 'FLAGSHIP POWER TIER',
      highlight: 'X3D Available • DDR5',
      cpuArchitecture: 'AMD Ryzen 7 7800X3D / 7900X',
      ramType: 'DDR5 ECC RAM',
      description: 'Peak single-thread performance for extreme workloads and high-slot game servers.',
    },
    {
      id: 'power-24gb',
      name: '24 GB VPS',
      category: 'power',
      monthlyPriceINR: 2869,
      monthlyPriceUSD: 35.86,
      vcpu: 8,
      ramGB: 24,
      storageNVMeGB: 120,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'Ryzen 7000 Series • DDR5',
      cpuArchitecture: 'AMD Ryzen 9 7900X / 7950X3D',
      ramType: 'DDR5 ECC RAM',
      description: '8-core Ryzen 7000 instance with 24 GB ultra-fast DDR5 RAM.',
    },
    {
      id: 'power-32gb',
      name: '32 GB VPS',
      category: 'power',
      monthlyPriceINR: 3804,
      monthlyPriceUSD: 47.55,
      vcpu: 10,
      ramGB: 32,
      storageNVMeGB: 160,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'X3D Available • DDR5',
      cpuArchitecture: 'AMD Ryzen 9 7950X / 7950X3D',
      ramType: 'DDR5 ECC RAM',
      description: '32 GB DDR5 Ryzen 7000 powerhouse.',
    },
    {
      id: 'power-64gb',
      name: '64 GB VPS',
      category: 'power',
      monthlyPriceINR: 6949,
      monthlyPriceUSD: 86.86,
      vcpu: 12,
      ramGB: 64,
      storageNVMeGB: 300,
      bandwidth: '1 Gbps Shared',
      ipv4: '1 Dedicated IPv4',
      virtualization: 'KVM',
      ddosProtection: 'Included',
      snapshots: 'Included',
      highlight: 'Maximum Performance Tier',
      cpuArchitecture: 'AMD Ryzen 9 7950X / 7950X3D',
      ramType: 'DDR5 ECC RAM',
      description: 'Ultimate Power tier with 12 Ryzen vCPU cores, 64 GB DDR5 RAM and 300 GB Gen4 NVMe.',
    },
  ] as VPSPlan[],

  // Supported Game Hosting Products
  games: [
    {
      id: 'minecraft',
      name: 'Minecraft Server Hosting',
      category: 'Sandbox / Survival',
      status: 'Available Now',
      isAvailable: true,
      description: 'High-clock single core performance for Paper, Purpur, Spigot, Fabric, and Forge servers.',
      startingPriceINR: 379,
      startingPriceUSD: 4.75,
      features: ['Paper / Purpur / Fabric', 'Instant Deployment', 'Automated Backups', 'DDoS Protection', 'Full SFTP & Panel Access'],
    },
    {
      id: 'palworld',
      name: 'Palworld Server Hosting',
      category: 'Open World Survival',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'High memory Dedicated Palworld instances with automatic restarts and save backups.',
      startingPriceINR: 616,
      startingPriceUSD: 7.70,
      features: ['Palworld Auto-Updates', 'High RAM Allocations', 'Save Protection', 'DDoS Shield'],
    },
    {
      id: 'rust',
      name: 'Rust Server Hosting',
      category: 'Action Survival',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'High CPU frequency nodes built for procedural Rust maps and oxide plugins.',
      startingPriceINR: 829,
      startingPriceUSD: 10.36,
      features: ['uMod / Oxide Support', 'Procedural Map Generator', 'DDoS Protection'],
    },
    {
      id: 'ark',
      name: 'ARK: Survival Evolved / Ascended',
      category: 'Survival',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'Enterprise storage and high memory allocations for heavy ARK maps and mods.',
      startingPriceINR: 829,
      startingPriceUSD: 10.36,
      features: ['Crossplay Support', 'Custom Mod Manager', 'NVMe Storage'],
    },
    {
      id: 'terraria',
      name: 'Terraria TShock Hosting',
      category: '2D Sandbox',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'Lightweight, ultra-stable Terraria vanilla and TShock server hosting.',
      startingPriceINR: 299,
      startingPriceUSD: 3.75,
      features: ['TShock & Modded', 'Low Latency', 'Instant Setup'],
    },
    {
      id: 'project-zomboid',
      name: 'Project Zomboid Server',
      category: 'Zombie Survival',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'Dedicated Zomboid servers with Steam Workshop mod integration.',
      startingPriceINR: 459,
      startingPriceUSD: 5.75,
      features: ['Steam Workshop Modding', 'Lua Config Controls', 'Auto Save'],
    },
    {
      id: 'valheim',
      name: 'Valheim Dedicated Server',
      category: 'Co-op Survival',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'Viking co-op world hosting with Valheim BepInEx modding support.',
      startingPriceINR: 459,
      startingPriceUSD: 5.75,
      features: ['BepInEx Mods', 'World Backups', 'Low Ping India Node'],
    },
    {
      id: 'fivem',
      name: 'FiveM / GTA V RP Hosting',
      category: 'Roleplay Server',
      status: 'Coming Soon',
      isAvailable: false,
      description: 'Low-latency India FiveM server hosting for txAdmin, ESX, QBCore, and custom resources.',
      startingPriceINR: 829,
      startingPriceUSD: 10.36,
      features: ['txAdmin Pre-Installed', 'ESX & QBCore Ready', 'High Bandwidth Network'],
    },
  ],

  // System Status Items (No fake uptime percentages)
  statusItems: [
    {
      id: 'control-panel',
      name: 'Customer Control Panel & API',
      status: 'Operational',
      state: 'green',
      detail: 'Core management portal, billing services, and provisioning API operating normally.',
    },
    {
      id: 'vps-nodes',
      name: 'Mumbai VPS Infrastructure Nodes',
      status: 'Operational',
      state: 'green',
      detail: 'KVM hypervisor hosts, EPYC/Xeon compute nodes, and NVMe arrays operating normally.',
    },
    {
      id: 'game-nodes',
      name: 'Game Server Compute Pool',
      status: 'Operational',
      state: 'green',
      detail: 'High-frequency Intel & Ryzen 7000 game compute nodes operating normally.',
    },
    {
      id: 'network-edge',
      name: '1 Gbps Network & DDoS Filtering',
      status: 'Operational',
      state: 'green',
      detail: 'Mumbai edge routers, NIXI peering links, and inline DDoS filtering active.',
    },
    {
      id: 'billing-gateway',
      name: 'Cashfree Payment Gateway',
      status: 'Operational',
      state: 'green',
      detail: 'UPI, GPay, Paytm, Cards, and NetBanking automated verification active.',
    },
  ] as SystemStatusItem[],

  // Operating Systems
  operatingSystems: [
    'Ubuntu 24.04 LTS (64-bit)',
    'Ubuntu 22.04 LTS (64-bit)',
    'Debian 12 Bookworm (64-bit)',
    'Debian 11 Bullseye (64-bit)',
    'AlmaLinux 9 (RHEL Compatible)',
    'Rocky Linux 9 (RHEL Compatible)',
    'CentOS Stream 9',
    'Docker Engine + Portainer Stack',
  ],

  // Technical FAQs
  faqs: [
    {
      question: 'How fast is server provisioning after checkout?',
      answer: 'VPS and Game Server deployments are automated. Once payment is confirmed by Cashfree, our API provisions your KVM instance, assigns your static IPv4, installs your chosen OS, and provides root credentials within 1-2 minutes.',
    },
    {
      question: 'What virtualization technology does KryonHost use?',
      answer: 'We use kernel-based virtual machine (KVM) hardware isolation across all VPS tiers. Your vCPU cores, RAM memory, and NVMe disk space are 100% dedicated to your instance with zero CPU overcommit or throttling.',
    },
    {
      question: 'What payment methods are accepted?',
      answer: 'We accept payments via Cashfree Payments Gateway, supporting UPI (Google Pay, PhonePe, Paytm, BHIM), RuPay, Visa, Mastercard, NetBanking, and credit/debit cards.',
    },
    {
      question: 'Can I upgrade or downgrade my VPS plan later?',
      answer: 'Yes, you can upgrade your VPS compute resources (vCPU, RAM, NVMe storage) or switch between Monthly and Quarterly billing anytime directly from your KryonHost Customer Dashboard.',
    },
    {
      question: 'Is DDoS Protection included?',
      answer: 'Yes, all KryonHost VPS and Game Server plans include always-on hardware DDoS mitigation against volume attacks at no extra charge.',
    },
    {
      question: 'Where is the KryonHost datacenter located?',
      answer: 'Our primary infrastructure node is hosted in a Tier IV facility in Mumbai, India, featuring direct domestic NIXI peering for sub-5ms low latency across India.',
    },
    {
      question: 'What is your refund policy?',
      answer: 'We offer a 48-hour money-back guarantee for new server instances if technical specifications or network connectivity fail to meet published parameters.',
    },
  ],
};
